version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

python:
  install:
    - requirements: all-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
