name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Style, python: '3.12', tox: style}
          - {name: '3.12', python: '3.12', tox: py312}
          - {name: '3.11', python: '3.11', tox: py311}
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: '3.8', python: '3.8', tox: py38}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox -e ${{ matrix.tox }}
